
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
// File Location: api/Zolos.ts

import { AxiosResponse, RawAxiosResponseHeaders, InternalAxiosRequestConfig, AxiosRequestHeaders, AxiosHeaders } from 'axios'
import { requestConfig } from '@prakerja/core-fe/build/core/axios.http.client'
import {
	GrantPermissionRequest,
	GrantPermissionResponse,
} from './CheckResult.types'

export const CheckResult = (
	params: GrantPermissionRequest,
	requestConfig: requestConfig,
) => {
	let g: GrantPermissionResponse = { 
		grantStatus: 99,
	}
	let cl = new AxiosHeaders()
    let headers: RawAxiosResponseHeaders = {}
    let xInternalHeaders: AxiosRequestHeaders = cl
    let conifg: InternalAxiosRequestConfig<undefined> = {
        headers: xInternalHeaders,
    }
    let resp: AxiosResponse<GrantPermissionResponse, undefined> = {
        data: g,
        status: 200,
        statusText: "OK",
        headers: headers,
        config: conifg
    }
	return new Promise<AxiosResponse<GrantPermissionResponse, undefined>>((resolve) => {
        resolve(resp)
    });
}
