
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
// File Location: api/Zolos.ts

import AxiosHttpClient, { requestConfig } from '@prakerja/core-fe/build/core/axios.http.client'
import {
	GrantPermissionRequest,
	GrantPermissionResponse,
} from './CheckResult.types'

const baseURL = process.env.REACT_APP_API_URL;

export const CheckResult = (
	params: GrantPermissionRequest,
	requestConfig: requestConfig,
) => {
	return AxiosHttpClient.post<GrantPermissionRequest, GrantPermissionResponse>(
		`${baseURL}/api/v1/facecapture/check`,
		params,
		requestConfig
	);
	
}
