// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
import React, { useState, createContext } from 'react';
import { GrantPermissionResponse } from './CheckResult.types';

export type ContextType = {
	get: () => GrantPermissionResponse | null;
	data: GrantPermissionResponse | null;
	set: (response: GrantPermissionResponse) => void;
}

const defaultCheckResultValues: ContextType = {
	data: null,
	set: () => {},
	get: () => null
}

type props = {
	children?: React.ReactNode
};

export const CheckResultContext =
  createContext<ContextType>(defaultCheckResultValues);

export const CheckResultProvider: React.FC<props> = ({ children }) => {
	const [data, setData] = useState< GrantPermissionResponse | null>(null);
	const set = (response: GrantPermissionResponse) => { 
		setData(response);
	}
	const get = () => data;

	return (
		<CheckResultContext.Provider
		  value= {{
			data,
			set,
		  }}
		>
		  {children}
		</CheckResultContext.Provider>
	  );
};
