package template

import lib "github.com/zokypesch/protoc-gen-react/lib"

var tmplTypes = `// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
{{- range $service := .Services }}
{{- range $method := $service.Methods }}
{{- range $msg := $method.MessageAll }}

{{- if not $msg.IsEmpty }}
export type {{ $msg.Name }} = { {{ range $field := $msg.Fields }}
	{{ $field.Name }} {{ if $field.IsOptional }}?{{- end }}: {{ $field.TypeData }};
	{{- end }}
}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
`

var Types = lib.List{
	Name:     "GenerateTypes",
	FileType: ".types.ts",
	Template: tmplTypes,
	Location: "./%s/%s/",
	Lang:     "ts",
}
