package template

import lib "github.com/zokypesch/protoc-gen-react/lib"

var tmplTypesAll = `
// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
{{- range $service := .Services }}
{{- range $method := $service.Methods }}
export { ContextType as {{ $method.Name }}ContextType } from './{{ $method.LocationPath }}/{{ $method.Name }}.context'
export { 
	{{- range $msg := $method.MessageAll }}
	{{ $msg.Name }} as {{ $method.Name }}_{{ $msg.Name }},
	{{- end }}
} from './{{ $method.LocationPath }}/{{ $method.Name }}.types'


{{- end }}
{{- end }}

`

// {{- range $msg := .Messages }}
// export type {{ $msg.Name }} = { {{ range $field := $msg.Fields }}
// 	{{ $field.Name }}: {{ $field.TypeData }};
// 	{{- end }}
// }
// {{- end }}

var TypesRef = lib.List{
	Name:     "GenerateAllTypes",
	FileType: ".all.types.ts",
	Template: tmplTypesAll,
	Location: "./%s/",
	Lang:     "wrapper",
}
