package template

import lib "github.com/zokypesch/protoc-gen-react/lib"

var tmplWrapper = `
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: {{ .FileName }}_{{ .GoPackage }}
// File Location: api/{{ ucfirst (getFirstService .Services).Name }}.ts
{{- range $service := .Services }}
{{- range $method := $service.Methods }}
export { 
	{{ $method.Name }}Provider,
	{{ $method.Name }}Context
} from './{{ $method.LocationPath }}/{{ $method.Name }}.context'

{{- end }}
{{- end }}
`

var Wrapper = lib.List{
	Name:     "GenerateWrapper",
	FileType: ".wrapper.tsx",
	Template: tmplWrapper,
	Location: "./%s/",
	Lang:     "wrapper",
}
