// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
import React, { useState, createContext } from 'react';
import { GrantPermissionResponse } from './GrantPermission.types';

export type ContextType = {
	get: () => GrantPermissionResponse | null;
	isAlreadyFetch: boolean;
	data: GrantPermissionResponse | null;
	set: (response: GrantPermissionResponse) => void;
}

const defaultGrantPermissionValues: ContextType = {
	isAlreadyFetch: false,
	data: null,
	set: () => {},
	get: () => null
}

type props = {
	children?: React.ReactNode
};

export const GrantPermissionContext =
  createContext<ContextType>(defaultGrantPermissionValues);

export const GrantPermissionProvider: React.FC<props> = ({ children }) => {
	const [data, setData] = useState< GrantPermissionResponse | null>(null); 
	const [isAlreadyFetch, setAlreadyFetch] = useState<boolean>(false);
	const set = (response: GrantPermissionResponse) => { 
		setData(response); 
		setAlreadyFetch(true);
	}
	const get = () => data;

	return (
		<GrantPermissionContext.Provider
		  value= {{
			isAlreadyFetch,
			data,
			set,
			get,
		  }}
		>
		  {children}
		</GrantPermissionContext.Provider>
	  );
};
