
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
// File Location: api/Zolos.ts
export { 
	GrantPermissionProvider,
	GrantPermissionContext
} from './get.facecapture.grant/GrantPermission.context'
export { 
	CheckResultProvider,
	CheckResultContext
} from './post.facecapture.check/CheckResult.context'
export { 
	GetAllTransHistoryByUserProvider,
	GetAllTransHistoryByUserContext
} from './get.facecapture.history/GetAllTransHistoryByUser.context'
