
// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
export { ContextType as GrantPermissionContextType } from './get.facecapture.grant/GrantPermission.context'
export {
	GrantPermissionResponse as GrantPermission_GrantPermissionResponse,
	GrantPermissionRequest as GrantPermission_GrantPermissionRequest,
} from './get.facecapture.grant/GrantPermission.types'
export { ContextType as CheckResultContextType } from './post.facecapture.check/CheckResult.context'
export {
	GrantPermissionResponse as CheckResult_GrantPermissionResponse,
	GrantPermissionRequest as CheckResult_GrantPermissionRequest,
} from './post.facecapture.check/CheckResult.types'
export { ContextType as GetAllTransHistoryByUserContextType } from './get.facecapture.history/GetAllTransHistoryByUser.context'
export {
	GrantPermissionResponse as GetAllTransHistoryByUser_GrantPermissionResponse,
	GrantPermissionRequest as GetAllTransHistoryByUser_GrantPermissionRequest,
} from './get.facecapture.history/GetAllTransHistoryByUser.types'

