
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: course.proto_coursesearch
// File Location: api/Coursesearch.ts

import AxiosHttpClient, { requestConfig } from '@prakerja/core-fe/build/core/axios.http.client'
import { BuildGetString } from '@prakerja/core-fe/build/core/utils.format'
import {
	GetCourseDetailRequest,
	GetCourseDetailResponse,
} from './GetCourseDetail.types'

const baseURL = process.env.REACT_APP_API_URL;

export const GetCourseDetail = (
	params: GetCourseDetailRequest,
	requestConfig: requestConfig,
) => {
	let buildString = BuildGetString(params)
	return AxiosHttpClient.get<undefined, GetCourseDetailResponse>(
		`${baseURL}/api/v1/coursesearch/detail/id${buildString}`,
		undefined,
		requestConfig
	);
	
}
