
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: course.proto_coursesearch
// File Location: api/Coursesearch.ts

import { AxiosResponse, RawAxiosResponseHeaders, InternalAxiosRequestConfig, AxiosRequestHeaders, AxiosHeaders } from 'axios'
import { requestConfig } from '@prakerja/core-fe/build/core/axios.http.client'
import {
	GetCourseDetailRequest,
	GetCourseDetailResponse,
} from './GetCourseDetail.types'

export const GetCourseDetail = (
	params: GetCourseDetailRequest,
	requestConfig: requestConfig,
) => {
	let g: GetCourseDetailResponse = { 
		id: 99, 
		name: "example name", 
		image_url: "example image_url", 
		amount: 99, 
		rating: "example rating", 
		total_rating: 99,  
		category: "example category", 
		duration: 99, 
		mentor_name: "example mentor_name", 
		level: "example level",   
		learning_method: "example learning_method",  
		description: "example description", 
		type: "example type", 
	}
	let cl = new AxiosHeaders()
    let headers: RawAxiosResponseHeaders = {}
    let xInternalHeaders: AxiosRequestHeaders = cl
    let conifg: InternalAxiosRequestConfig<undefined> = {
        headers: xInternalHeaders,
    }
    let resp: AxiosResponse<GetCourseDetailResponse, undefined> = {
        data: g,
        status: 200,
        statusText: "OK",
        headers: headers,
        config: conifg
    }
	return new Promise<AxiosResponse<GetCourseDetailResponse, undefined>>((resolve) => {
        resolve(resp)
    });
}
