// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: course.proto_coursesearch
export type CoursePlatform = { 
	id : number;
	company ?: Company;
	url : string;
	status : number;
}
export type CourseRequirement = { 
	key : string;
	min : string;
	max : string;
}
export type Instructor = { 
	id : number;
	name : string;
	photo : string;
	type : string;
	total_students : string;
	total_courses : string;
}
export type GetCourseDetailRequest = { 
	id : number;
}
export type GetCourseDetailResponse = { 
	id : number;
	name : string;
	image_url : string;
	amount : number;
	rating : string;
	total_rating : number;
	lembaga_pelatihan ?: Company;
	category : string;
	duration : number;
	mentor_name : string;
	level : string;
	platforms ?: CoursePlatform[];
	course_requirement ?: CourseRequirement[];
	learning_method : string;
	rating_group ?: number[];
	description : string;
	type : string;
	instructor ?: Instructor[];
}
export type Company = { 
	id : number;
	name : string;
	logo : string;
	url : string;
}
