// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: course.proto_coursesearch
import React, { useState, createContext } from 'react';
import { GetCourseDetailResponse } from './GetCourseDetail.types';

export type ContextType = {
	get: () => GetCourseDetailResponse | null;
	isAlreadyFetch: boolean;
	data: GetCourseDetailResponse | null;
	set: (response: GetCourseDetailResponse) => void;
}

const defaultGetCourseDetailValues: ContextType = {
	isAlreadyFetch: false,
	data: null,
	set: () => {},
	get: () => null
}

type props = {
	children?: React.ReactNode
};

export const GetCourseDetailContext =
  createContext<ContextType>(defaultGetCourseDetailValues);

export const GetCourseDetailProvider: React.FC<props> = ({ children }) => {
	const [data, setData] = useState< GetCourseDetailResponse | null>(null); 
	const [isAlreadyFetch, setAlreadyFetch] = useState<boolean>(false);
	const set = (response: GetCourseDetailResponse) => { 
		setData(response); 
		setAlreadyFetch(true);
	}
	const get = () => data;

	return (
		<GetCourseDetailContext.Provider
		  value= {{
			isAlreadyFetch,
			data,
			set,
			get,
		  }}
		>
		  {children}
		</GetCourseDetailContext.Provider>
	  );
};
