
// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: course.proto_coursesearch
export { ContextType as GetCourseDetailContextType } from './get.detail.id/GetCourseDetail.context'
export {
	CoursePlatform as GetCourseDetail_CoursePlatform,
	CourseRequirement as GetCourseDetail_CourseRequirement,
	Instructor as GetCourseDetail_Instructor,
	GetCourseDetailRequest as GetCourseDetail_GetCourseDetailRequest,
	GetCourseDetailResponse as GetCourseDetail_GetCourseDetailResponse,
	Company as GetCourseDetail_Company,
} from './get.detail.id/GetCourseDetail.types'

