
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: course.proto_coursesearch
// File Location: api/Coursesearch.ts
export { 
	GetCourseDetailProvider,
	GetCourseDetailContext
} from './get.detail.id/GetCourseDetail.context'
