
// Code generated by sangkuriang protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
// File Location: api/Zolos.ts

import AxiosHttpClient, { requestConfig } from '@prakerja/core-fe/build/core/axios.http.client'
import {
	GrantPermissionRequest,
} from './GetAllTransHistoryByUser.types'

const baseURL = process.env.REACT_APP_API_URL;

export const GetAllTransHistoryByUser = (
	requestConfig: requestConfig,
) => {
	return AxiosHttpClient.get<undefined, GrantPermissionRequest>(
		`${baseURL}/api/v1/facecapture/history`,
		undefined,
		requestConfig
	);
	
}
