// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
export type GrantPermissionResponse = { 
	grantStatus : number;
}
export type GrantPermissionRequest = { 
	user_id : number;
	items ?: number[];
	data ?: GrantPermissionResponse;
	data_test ?: GrantPermissionResponse[];
}
