// TANGKUBAN PERAHU
// Code generated by dayang sumbi protoc-gen-go. DO NOT EDIT.
// source: example.proto_zolos
import React, { useState, createContext } from 'react';
import { GrantPermissionRequest } from './GetAllTransHistoryByUser.types';

export type ContextType = {
	get: () => GrantPermissionRequest | null;
	isAlreadyFetch: boolean;
	data: GrantPermissionRequest | null;
	set: (response: GrantPermissionRequest) => void;
}

const defaultGetAllTransHistoryByUserValues: ContextType = {
	isAlreadyFetch: false,
	data: null,
	set: () => {},
	get: () => null
}

type props = {
	children?: React.ReactNode
};

export const GetAllTransHistoryByUserContext =
  createContext<ContextType>(defaultGetAllTransHistoryByUserValues);

export const GetAllTransHistoryByUserProvider: React.FC<props> = ({ children }) => {
	const [data, setData] = useState< GrantPermissionRequest | null>(null); 
	const [isAlreadyFetch, setAlreadyFetch] = useState<boolean>(false);
	const set = (response: GrantPermissionRequest) => { 
		setData(response); 
		setAlreadyFetch(true);
	}
	const get = () => data;

	return (
		<GetAllTransHistoryByUserContext.Provider
		  value= {{
			isAlreadyFetch,
			data,
			set,
			get,
		  }}
		>
		  {children}
		</GetAllTransHistoryByUserContext.Provider>
	  );
};
